config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'filebox#index'
  get 'filebox' => 'filebox#index'
  get 'login' => 'filebox#login'
  
  get 'filebox/:folder_id/item/:item_id/show_image' => 'filebox#show_image', as: 'show_image'
  
  get 'filebox/:folder_id/item/:item_id/download' => 'filebox#download_file', as: 'download_file'

  delete 'filebox/:folder_id/item/:item_id/delete_item' => 'filebox#delete_item', as: 'delete_item'
  
  get 'filebox/:folder_id/get_folders_and_items' => 'filebox#get_folders_and_items'

  resources :filebox do
    post 'create_file' => 'filebox#create_file'
  end

  resources :folder
  resources :item

  get 'api/get_key' => 'api/api#get_key'
  get 'api/regenerate_key' => 'api/api#regenerate_key'

  namespace :api do
    resources :api, path: '', except: [:show, :edit, :update, :new, :update, :destroy, :create]
    resources :folder
    resources :item
  end

end

app/controllers/filebox_controller.rb
class FileboxController < ApplicationController

  #before_action :authenticate_user!, :except => [:index, :login]

  def index
    redirect_to login_path and return if !user_signed_in?
    create_root_folder_if_missing
    withdraw_items
    @folder_list = @root_folder
    @file = Item.new
    @folders = folder_hash(withdraw_root_folder)
  end 

  def create
    withdraw_items
    new_file = @root_folder.first.item.new()
    if !params[:item].nil?
      create_file(new_file)
    end
    
    if new_file.save
      redirect_to filebox_index_path, :notice => "Dodano"
    else
      redirect_to filebox_index_path, :alert => "Nie dodano"
    end
  end

  def withdraw_items
    @root_folder = withdraw_root_folder
    @folder = folder_hash(@root_folder)
  end

  def folder_hash(main_folder)
    hash_array = []
    main_folder.each do |folder|
      ret_hash = {
        :id => folder.id.to_s,
        :name => folder.name,
        :is_directory => true,
        :size => folder.size,
        :children => folder_hash(folder.children),
        :items => []
      }
      hash_array << ret_hash
    end
    return hash_array
  end
  
  def item_hash(item)
    ret_hash = {
      :id => item.id.to_s,
      :name => item.name,
      :is_directory => false,
      :size => item.size,
      :children => []
    }
    return ret_hash
  end
  
  def withdraw_root_folder
    if current_user.is_admin?
      list = []
      User.all.each { |u| list << u.folder if !u.folder.nil?}
      return list
    else
      return [current_user.folder]
    end
  end

  def create_root_folder_if_missing
    current_user.create_root_folder if current_user.folder.nil?
  end

  def create_file(new_file)
    new_file.attachment = params[:item][:attachment]
    new_file.name = new_file.filename
  end

  def download_file
    file = Folder.find(params[:folder_id]).item.find(params[:item_id])
    send_file file.attachment.url
  end

  def show_image
    file  = Folder.find(params[:folder_id]).item.find(params[:item_id])
    if file.is_image?
      url = file.attachment.url
      send_file url, :type => 'image/jpeg', :disposition => 'inline'
    end
  end 

  def delete_item
    file  = current_user.folder.item.find(params[:item_id])
    delete_attachment_from_hdd(file)
    if file.delete
      render :json => {:notice => "Ok"}
    else
      render :json => {:notice => "Nope."}
    end
  end

  def delete_attachment_from_hdd(file)
    File.delete(file.attachment.url) if File.exist? file.attachment.url
  end

  def get_folders_and_items
    @folder = Folder.find(params[:folder_id])
    folder = @folder # testowo
    return_hash = {}

    return_hash[:id] = folder.id.to_s
    return_hash[:name] = folder.name
    return_hash[:type] = "dir"
    return_hash[:ext] = false
    return_hash[:size] = folder.size
    return_hash[:items] = []
    #@folder.each do |folder|
      folder.item.each do |item|
        item_hash = {}
        item_hash[:id] = item.id.to_s
        item_hash[:name] = item.name
        item_hash[:type] = "file"
        item_hash[:ext] = "image" if item.is_image?
        item_hash[:ext] = "unknown" if !item.is_image?
        item_hash[:size] = item.size
        return_hash[:items] << item_hash
      end
    #end
    render :json => folder_hash(withdraw_root_folder)
  end

end

app/views/filebox/_content.html.erb
<ul class="list-inline">
  <li onclick="fadeNewFileForm()" class="hover">
    <span class="fa-stack">
      <i class="fa fa-file-o fa-stack-2x"></i>
      <i class="fa fa-plus fa-stack-1x"></i>
    </span>
    Dodaj plik
  </li>
  <li class="hover">
    <span class="fa-stack">
      <i class="fa fa-folder-o fa-stack-2x"></i>
      <i class="fa fa-plus fa-stack-1x"></i>
    </span>
    Dodaj folder
  </li>
</ul>

<div class="filebox-container filebox-title">
  <div class="name">
    Nazwa
  </div>
  <div class="size">
    Rozmiar
  </div>  
  <div class="options">
    Opcje
  </div>
</div>

<div id="slidable" style="display:none;">

<% @folder_list.each do |folder| %>
  <div class="filebox-container" style="opacity: 0.2;">
    <a href="javascript:void(0)">
      <div class="name">
        <i class="fa fa-folder-o fa-lg"></i> 
        <%= folder.name %>
      </div>
    </a>
    <div class="size">
      <%= number_to_human_size folder.size %>
    </div>
    <div class="options">
      <i class="fa fa-download fa-lg" style="color: white;"></i>   
      <i class="fa fa-cog fa-lg"></i>
      <i class="fa fa-pencil fa-lg"></i>
      <i class="fa fa-times fa-lg"></i>
    </div>
  </div>
  
  <% folder.item.each_with_index do |item, i| %>
  <div id="<%= item.id %>" class="filebox-container">
    <%= link_to show_image_path(:folder_id => item.folder, :item_id => item) do %>
      <div class="name-item">
        <% if item.is_image? %>
          <i class="fa fa-file-image-o fa-lg"></i> 
        <% else %>
          <i class="fa fa-file-o fa-lg"></i>
        <% end %>
        
        <% if item.attachment.url.nil? %>
          <%= "abcdefgh"[1..rand(7)+1] %>.ext
        <% else %>
          <%= item.filename %>
        <% end %>
      </div>
    <% end %>
    <div class="size">
      <%= number_to_human_size item.size %>
    </div>
    <div class="options">
      <%= link_to download_file_path(:folder_id => item.folder, :item_id => item) do %>
        <i class="fa fa-download fa-lg"></i>     
      <% end %>
      <i class="fa fa-cog fa-lg"></i>
      <i class="fa fa-pencil fa-lg"></i>
      <a id="<%= item.id %>_a" href="javascript:void(0)" onClick='deleteFile("<%= item.folder.id %>", "<%= item.id %>")'>
        <i class="fa fa-times fa-lg"></i>
      </a>
    </div>
  </div>
  <% end %>

<% end %>
</div>

<div class="filebox-container filebox-footer">
  <div class="name">
    <%= @folder_list.count %> folder, X plików
  </div>
  <div class="options">
    
  </div>
</div>


<div class="new-file-form"></div>

<style>

#jumbotron-content {
  height: 100px;
  border: 0px lightgray solid ;
}
.body-shadow {
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  position: absolute;
  background-color: #000;
  display: none;
  opacity: 0.5;
  z-index: 1;
}
.new-file-form{
  position: absolute;
  z-index: 2;
  border: 2px black solid;
  border-radius: 10px;
  width: 500px;
  height: 300px;
  top: 5%;
  left: 10%;
  display: none;
}
</style>
<script>

function fadeNewFileForm() {
  $('#jumbotron-content').fadeOut('fast', function(){
    $('#jumbotron-content').html('<%= escape_javascript(render('new_file')).html_safe %>');
    $('#jumbotron-content').fadeIn();
  });
};

$('#slidable').slideDown();

function deleteFile(folder_id, file_id){
  var cross = $('#' + file_id + '_a')
  cross.fadeOut('fast', function(){
    cross.html('<i class="fa fa-spinner fa-spin"></i>');
    cross.fadeIn('fast');
  });

  $.ajax({
    url: "/filebox/" + folder_id + "/item/" + file_id + "/delete_item",
    type: 'DELETE',
    success: function(result) {
      cross.fadeOut('fast', function(){
        cross.html('<i class="fa fa-check"></i>');
        cross.fadeIn('fast', function(){
          $('#'+file_id).slideUp()
        });
      });
    }    
  });

};

var jso = $.get("http://selandir.pl:3000/filebox/#{@folder_list.first.id.to_s}/get_folders_and_items.json");
console.log(jso);
</script>

app/views/filebox/_new_file.html.erb
<div class="row">
<div class="col-md-4">
<%= simple_form_for @file, :url => {:action => "create"}, :html => {:class => "form-inline"} do |f| %>

  <div class="form-group">
    <%= f.input :attachment, :label => false, :as => "file", :wrapper => false, :input_html => {:class => ""}, multiple: true %>
  </div>
  <br> <br>
  <div class="form-group">
    <%= f.button :submit, :wrapper => false, :class => "btn btn-primary" %>
    <%#= link_to t('cancel'), @file.new? ? filebox_index_path : filebox_path(@file), :class => "btn" %>
  </div>

<% end %>
</div>
</div>

app/views/filebox/index.html.erb
<%= render 'menus/top_bar' %>

<div class="container">
  <div class="jumbotron">
    <div id="jumbotron-content">
      <center>
        <span class="logo">File<strong>Box</strong></span>
        <p class="lead">The <span style="color: #666;">File</span><span style="color: #779ECB;">Box</span> is my own file storage system. Yes, it is not finished yet.</p>
      </center>
    </div>
  </div>
  <% if user_signed_in? %>
  <div class="row">
    <div class="col-md-12">
    <%= render 'content' %>
    </div>
  </div>
  
  <% end %>

  <div class="todo">
  Todo:
  <div style="float:right;"><i class="fa fa-calendar-check-o fa-lg"></i></div>
  <ul class="fa-ul">
    <li><i class="fa-li fa fa-check-square"></i>Main view</li>
    <li><i class="fa-li fa fa-check-square"></i>File upload</li>
    <li><i class="fa-li fa fa-check-square"></i>Ajax file removal</li>
    <li><i class="fa-li fa fa-check-square"></i>File left-padding</li>
    <li><i class="fa-li fa fa-check-square"></i>Image preview</li>
    <li><i class="fa-li fa fa-check-square"></i>File download</li>
    <li><i class="fa-li fa fa-spinner fa-spin"></i>Folders</li>
    <li><i class="fa-li fa fa-square"></i>Gravatars/Identicons</li>
    <li><i class="fa-li fa fa-square"></i>Sharing files & folders</li>
    <li><i class="fa-li fa fa-square"></i>Ajax file upload</li>
    <li><i class="fa-li fa fa-square"></i>File name change</li>
    <li><i class="fa-li fa fa-square"></i>Upload wihout registration</li>
    <li><i class="fa-li fa fa-square"></i>Permissions</li>
    <li><i class="fa-li fa fa-square"></i>API</li>

  </ul>
  </div>  
</div> <!-- /container -->


<style>

.todo {
    padding: 5px;
    border-radius: 5px;
    height: 500px;
    width: 300px;
    position:absolute;
    top:20%;
    left:-270px;
    border: 3px #dadada solid;
    transition: left ease 0.5s, transform 0.5s;
    background-color: #f5f5f5;
}

.todo:hover {
  left: -2%;
  transform: rotate(12deg);
}
.hover{
  margin-left: 10px;
  padding: 5px;
  background-color: #F6F6F6;
  border-radius: 5px;
}
.hover:hover {
  background-color: #F0F0F0;
}
.logo {
  border: 2px #779ECB solid;
  border-radius: 5px;
  padding: 5px 15px 5px 15px;
  font-family: "Helvetica";
  font-size: 47px;
  color: #777;
}

.logo:hover {
background-color: #e7eEfB;
}

.logo strong{
color: #779ECB;
font-weight: normal;
}

.filebox-container {
  border-radius: 2px;
  padding: 0px 0px 0px 0px;
  border: 0px black solid;
  width: 100%;
  height: 40px;
  margin: 2px 0px 2px 0px;
}

.filebox-title {
  border-radius: 10px 10px 0px 0px;
  border-bottom: 2px #ddd solid;
  padding: 5px 5px 5px 5px;
  width: 100%;
}

.filebox-footer {
  border-radius: 0px 0px 10px 10px;
  border-top: 2px #ddd solid;
  padding: 5px 5px 5px 5px;
  width: 100%;
}

.filebox-container a {
  color: inherit;
}

.filebox-container a:hover {
  color: #779ECB;
  text-decoration: none;
}

.filebox-container:nth-child(even) {
  background-color: #F6F6F6;
}

.filebox-container:nth-child(odd) {
  background-color: #FAFAFA;
}

.filebox-container:hover {
background-color: #e7eEfB;
}

.filebox-container .name {
padding: 10px 0px 0px 10px;
border: 0px black solid;
height: 100%  ;
width: 70%;
float: left;
}

.filebox-container .name-item {
padding: 10px 0px 0px 20px;
border: 0px black solid;
height: 100%  ;
width: 70%;
float: left;
}

.filebox-container .options {
padding: 10px 0px 0px 10px;
border: 0px black solid;
height: 100%  ;
width: 18%;
float: left;
}

.filebox-container .size {
padding: 10px 0px 0px 10px;
border: 0px black solid;
height: 100%  ;
width: 10%;
float: left;
}

</style>

app/views/filebox/login.html.erb
<div class="navbar navbar-default">
  <div class="container">
    
    <ul class="nav navbar-nav">
      
    </ul>

  </div>
</div>  

<%= render 'devise/sessions/form' %>

app/views/filebox/show_image.html.erb
<%= yield %>